#tocmat设置
server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
#    允许的http请求
  port-header: HEAD,PUT,DELETE,OPTIONS,TRACE,COPY,SEARCH,PROPFIND
#  spring设置
spring:
#配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
#jpa相关配置
  jpa:
    hibernate:
      ddl-auto: update  # 第一次简表create  后面用update 实践证明第一次也可以update
    show-sql: true
#     控制台彩色输出
  output:
    ansi:
      enabled: ALWAYS
#mail
  mail:
    host: smtp.163.com
    username: xuesemofa@126.com
    password: liudong1013
    port: 25
    protocol: smtp
    default-encoding: UTF-8
#    页面
  thymeleaf:
    prefix: classpath:/templates
    encoding: UTF-8
    #缓存
    cache: false
  #表示所有的访问都经过静态资源路径；
  mvc:
    static-path-pattern: /**
  #在这里配置静态资源路径，前面说了这里的配置是覆盖默认配置，
  #所以需要将默认的也加上否则static、public等这些路径将不能被当作静态资源路径，
  #在这个最末尾的file:${web.upload-path}之所有要加file:是因为指定的是一个具体的硬盘路径，
  #其他的使用classpath指的是系统环境变量
  resources:
    static-locations: classpath:/static/,classpath:/public/,file:${file.filePath}
#    缓存
#可选值
#simple: 基于ConcurrentHashMap实现的缓存，适合单机或者开发环境使用。
#none：关闭缓存，比如开发阶段先确保功能正确，可以先禁止使用缓存
#redis：使用redis作为缓存，你还需要在pom里增加redis依赖。本章缓存将重点介绍redis缓存以及扩展redis实现一二级缓存
#Generic，用户自定义缓存实现，用户需要实现一个org.springframework.cache.CacheManager的实现
  cache:
    type: simple
#自定义分页条数
page:
  pageSize: 15
#文件上传地址
file:
  filePath: D://
#  shiro
shiro:
  token:
    key: usertoken
    expirateTime: 900